# Generated by Django 4.1.3 on 2022-11-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('max_value', models.IntegerField()),
                ('min_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('buttons', models.ManyToManyField(related_name='buttons', to='bots.button')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('max_value', models.IntegerField()),
                ('min_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ValueDisplay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('max_value', models.IntegerField()),
                ('min_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('serial_number', models.CharField(max_length=50)),
                ('controls', models.ManyToManyField(to='bots.controls')),
                ('parts', models.ManyToManyField(to='bots.part')),
            ],
        ),
        migrations.AddField(
            model_name='controls',
            name='slider',
            field=models.ManyToManyField(related_name='slider', to='bots.slider'),
        ),
        migrations.AddField(
            model_name='controls',
            name='valuedisplay',
            field=models.ManyToManyField(related_name='valuedisplay', to='bots.valuedisplay'),
        ),
    ]
